// Generated by Haxe 5.0.0-preview.1
(function ($global) { "use strict";
class audioWorklets_LocalVoiceAudioWorklet extends AudioWorkletProcessor {
	constructor() {
		super();
		this.waveformPosition = 0;
		this.fmWaveformPosition = 0;
		this.fm2WaveformPosition = 0;
		this.harmonics = [];
		let _gthis = this;
		this.port.onmessage = function(e) {
			_gthis.harmonics = e.data.harmonics;
			let maxAmplitude = 0;
			let _g_current = 0;
			let _g_array = _gthis.harmonics;
			while(_g_current < _g_array.length) {
				let _g_value = _g_array[_g_current];
				let _g_key = _g_current++;
				let harmonic = _g_key;
				let harmonicInfo = _g_value;
				if(harmonicInfo.a > maxAmplitude) {
					maxAmplitude = harmonicInfo.a;
				}
			}
			let _g_current1 = 0;
			let _g_array1 = _gthis.harmonics;
			while(_g_current1 < _g_array1.length) {
				let _g_value = _g_array1[_g_current1];
				let _g_key = _g_current1++;
				let harmonic = _g_key;
				let harmonicInfo = _g_value;
				harmonicInfo.a /= maxAmplitude;
			}
		};
	}
	process(inputs,outputs,parameters) {
		let output = outputs[0];
		let _g = 0;
		let _g1 = output[0].length;
		while(_g < _g1) {
			let i = _g++;
			let leftVolume = parameters.volume[parameters.volume.length > 1 ? i : 0] * .25;
			let rightVolume = leftVolume;
			if(parameters.enabled[0] == 0 || leftVolume == 0 && rightVolume == 0) {
				this.waveformPosition = this.fmWaveformPosition = this.fm2WaveformPosition = 0;
				continue;
			}
			leftVolume *= Math.min(1,1 - parameters.pan[parameters.pan.length > 1 ? i : 0]);
			rightVolume *= Math.min(1,parameters.pan[parameters.pan.length > 1 ? i : 0] + 1);
			this.fm2WaveformPosition += parameters.fm2Speed[parameters.fm2Speed.length > 1 ? i : 0] / sampleRate;
			this.fmWaveformPosition += parameters.fmSpeed[parameters.fmSpeed.length > 1 ? i : 0] / sampleRate;
			this.waveformPosition += parameters.pitch[parameters.pitch.length > 1 ? i : 0] / sampleRate;
			let phase = this.waveformPosition + parameters.fmAmplitude[parameters.fmAmplitude.length > 1 ? i : 0] * Math.sin((this.fmWaveformPosition + parameters.fm2Amplitude[parameters.fm2Amplitude.length > 1 ? i : 0] * Math.sin(this.fm2WaveformPosition * 2 * Math.PI)) * 2 * Math.PI);
			let _g1 = 0;
			let _g2 = this.harmonics;
			while(_g1 < _g2.length) {
				let harmonic = _g2[_g1];
				++_g1;
				output[0][i] += Math.sin(phase * harmonic.f * 2 * Math.PI + harmonic.p) * harmonic.a * leftVolume;
				output[1][i] += Math.sin(phase * harmonic.f * 2 * Math.PI + harmonic.p) * harmonic.a * rightVolume;
			}
		}
		return true;
	}
	static main() {
		registerProcessor("LocalVoiceAudioWorklet",audioWorklets_LocalVoiceAudioWorklet);
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
audioWorklets_LocalVoiceAudioWorklet.parameterDescriptors = [{ name : "pitch", defaultValue : 0, minValue : 0, maxValue : 10000},{ name : "volume", defaultValue : 0, minValue : 0, maxValue : 1},{ name : "pan", defaultValue : 0, minValue : -1, maxValue : 1},{ name : "fmSpeed", defaultValue : 0, minValue : 0, maxValue : 10000},{ name : "fmAmplitude", defaultValue : 0, minValue : 0, maxValue : 24},{ name : "fm2Speed", defaultValue : 0, minValue : 0, maxValue : 10000},{ name : "fm2Amplitude", defaultValue : 0, minValue : 0, maxValue : 24},{ name : "enabled", defaultValue : 1, minValue : 0, maxValue : 1}];
audioWorklets_LocalVoiceAudioWorklet.main();
})({});
