// Generated by Haxe 5.0.0-preview.1
(function ($global) { "use strict";
class audioWorklets_ProceduralAudioWorklet extends AudioWorkletProcessor {
	constructor() {
		super();
		this.waveformPosition = 0;
		this.fmWaveformPosition = 0;
		this.fm2WaveformPosition = 0;
	}
	process(inputs,outputs,parameters) {
		let output = outputs[0];
		let _g = 0;
		let _g1 = output[0].length;
		while(_g < _g1) {
			let i = _g++;
			let leftVolume = parameters.volume[parameters.volume.length > 1 ? i : 0] * .25;
			let rightVolume = leftVolume;
			if(parameters.enabled[0] == 0 || leftVolume == 0) {
				this.waveformPosition = this.fmWaveformPosition = this.fm2WaveformPosition = 0;
				continue;
			}
			leftVolume *= Math.min(1,1 - parameters.pan[parameters.pan.length > 1 ? i : 0]);
			rightVolume *= Math.min(1,parameters.pan[parameters.pan.length > 1 ? i : 0] + 1);
			this.fm2WaveformPosition += parameters.fm2Speed[parameters.fm2Speed.length > 1 ? i : 0] / sampleRate;
			this.fmWaveformPosition += parameters.fmSpeed[parameters.fmSpeed.length > 1 ? i : 0] / sampleRate;
			this.waveformPosition += parameters.pitch[parameters.pitch.length > 1 ? i : 0] / sampleRate;
			let phase = this.waveformPosition + parameters.fmAmplitude[parameters.fmAmplitude.length > 1 ? i : 0] * Math.sin((this.fmWaveformPosition + parameters.fm2Amplitude[parameters.fm2Amplitude.length > 1 ? i : 0] * Math.sin(this.fm2WaveformPosition * 2 * Math.PI)) * 2 * Math.PI);
			switch(Math.floor(parameters.waveform[parameters.waveform.length > 1 ? i : 0])) {
			case 0:
				output[0][i] += Math.sin(phase * 2 * Math.PI) * leftVolume;
				output[1][i] += Math.sin(phase * 2 * Math.PI) * rightVolume;
				break;
			case 1:
				let harmonics = parameters.harmonics[parameters.harmonics.length > 1 ? i : 0];
				let _g1 = 1;
				let _g2 = Math.ceil(harmonics);
				while(_g1 < _g2) {
					let harmonic = _g1++;
					let harmonicFade = harmonic == Math.floor(harmonics) && harmonics != Math.floor(harmonics) ? harmonics % 1 : 1;
					output[0][i] += Math.sin(phase * harmonic * 2 * Math.PI) / harmonic * leftVolume / 2 * harmonicFade;
					output[1][i] += Math.sin(phase * harmonic * 2 * Math.PI) / harmonic * rightVolume / 2 * harmonicFade;
				}
				break;
			case 2:
				let harmonics1 = parameters.harmonics[parameters.harmonics.length > 1 ? i : 0];
				let _g3 = 1;
				let _g4 = Math.ceil(harmonics1);
				while(_g3 < _g4) {
					let harmonic = _g3++;
					let harmonicFade = harmonic == Math.floor(harmonics1) && harmonics1 != Math.floor(harmonics1) ? harmonics1 % 1 : 1;
					output[0][i] += Math.sin(phase * (harmonic * 2 - 1) * 2 * Math.PI) / (harmonic * 2 - 1) * leftVolume * harmonicFade;
					output[1][i] += Math.sin(phase * (harmonic * 2 - 1) * 2 * Math.PI) / (harmonic * 2 - 1) * rightVolume * harmonicFade;
				}
				break;
			case 3:
				let harmonics2 = parameters.harmonics[parameters.harmonics.length > 1 ? i : 0];
				let _g5 = 1;
				let _g6 = Math.ceil(harmonics2);
				while(_g5 < _g6) {
					let harmonic = _g5++;
					let harmonicFade = harmonic == Math.floor(harmonics2) && harmonics2 != Math.floor(harmonics2) ? harmonics2 % 1 : 1;
					output[0][i] += Math.sin(phase * (harmonic * 2 - 1) * 2 * Math.PI) / Math.pow(harmonic * 2 - 1,2) * Math.pow(-1,harmonic - 1) * leftVolume * harmonicFade;
					output[1][i] += Math.sin(phase * (harmonic * 2 - 1) * 2 * Math.PI) / Math.pow(harmonic * 2 - 1,2) * Math.pow(-1,harmonic - 1) * rightVolume * harmonicFade;
				}
				break;
			}
		}
		return true;
	}
	static main() {
		registerProcessor("ProceduralAudioWorklet",audioWorklets_ProceduralAudioWorklet);
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
audioWorklets_ProceduralAudioWorklet.parameterDescriptors = [{ name : "waveform", defaultValue : 0, minValue : 0, maxValue : 3},{ name : "pitch", defaultValue : 0, minValue : 0, maxValue : 10000},{ name : "volume", defaultValue : 0, minValue : 0, maxValue : 2},{ name : "pan", defaultValue : 0, minValue : -1, maxValue : 1},{ name : "harmonics", defaultValue : 50, minValue : 1, maxValue : 50},{ name : "fmSpeed", defaultValue : 0, minValue : 0, maxValue : 10000},{ name : "fmAmplitude", defaultValue : 0, minValue : 0, maxValue : 24},{ name : "fm2Speed", defaultValue : 0, minValue : 0, maxValue : 10000},{ name : "fm2Amplitude", defaultValue : 0, minValue : 0, maxValue : 24},{ name : "enabled", defaultValue : 1, minValue : 0, maxValue : 1}];
audioWorklets_ProceduralAudioWorklet.main();
})({});
